#===========================[BASE CONFIG]===========================
MERCHANTID=100000000087600
POSID=60011366
BASE_MERCHANT_NAME=Test Store
MERCHANTNAME=BBL UAT TEST MERCHANT
BASE_TRACE_NO=000001
TRACENO=000001
BATCHNO=000001
BASE_CURRENCY_CODE=050
CURRENCYTYPE=0
MENUTITLE=BRAC MERCHANT POS

#===========================[ADDRESSES]===========================
MERCHANTADDR1=
MERCHANTADDR2=BRAC BANK PLC, ADC DEPARTMENT
MERCHANTADDR3=TEJGAON I/A, DHAKA
MERCHANTADDR4=
MERCHANTADDR5=

#===========================[EMI CONFIG]===========================
EMIMERCHANTID=100000000087600
EMIPOSID=40011366
EMIMERCHANTNAME=BRAC EMI POS
EMIBATCHNO=000001
EMITENURE=3,6,9,12,18,24,36
EMIVENDOR=BBL:1111111
EMIPRODUCTID=9999
EMIFLOORLIMIT=000000000000
TENURELIMIT=99

#===========================[LIMITS & TIMEOUTS]===========================
BASE_MAX_REFUND_AMOUNT=1000000
BASE_MAX_TRANS_COUNT=500
MAXTRANSCOUNT=999
MAXPRECOUNT=999
UPAMT=000099999999
LOWAMT=000000000000
CARD_READER_TIMEOUT=60
IDLETIMEOUT=30
SAVER_SCREEN_TIME=15000
OUTOFAPAPERTIMEOUT=60
TESTTXNTIME=30

#===========================[PINPAD & CONTACTLESS]===========================
PINPAD_TIMEOUT=60
PINPAD_ACCESSIBILITY_TIMEOUT=120
PINPAD_EXTERNAL=0
PINPAD_EXTERNAL_CONNECT_MODE=0
BYPASSPIN=0
RANDOMPINPAD=1
PPCVMLIMIT=000000500001
PPFLOORLIMIT=000000000000
PWCVMLIMIT=000000500001
PWFLOORLIMIT=000000000000

#===========================[TRANSACTIONS SUPPORT]===========================
TRANS_SALE=1
SALE=1
TRANS_VOID=1
VOID=1
TRANS_REFUND=1
TRANS_BALANCE=1
BALANCE=0
TRANS_PREAUTH=1
PREAUTH=1
TRANS_MOBILE_PAY=1
TRANS_INSTALLMENT=1
TRANS_CASH_ADVANCE=1
TRANS_CASH_BACK=1
EMI=1
SALECOMP=1
OFFLINE=1
ADJUST=1
FALLBACKFLAG=0
OTHER_THIRD_BILL_SHOW=0
OTHER_VOID_CARD=1
OTHER_VOID_PIN=1

#===========================[PRINTER & RECEIPTS]===========================
PRINT_EXTERNAL=0
PRINT_EXTERNAL_CONNECT_MODE=1
PRINT_EXTERNAL_SERIAL_BAUDRATE=115200
PRINT_REMARKS=
FOOTER1=I AGREE TO PAY THE ABOVE TOTAL AMOUNT
FOOTER2=TO CARD ISSUER AGREEMENT 01234567890
FOOTER3=TO CARD ISSUER AGREEMENT 01234567890
FOOTER4=TO CARD ISSUER AGREEMENT 01234567890
COPY1=MERCHANT COPY
COPY2=CUSTOMER COPY
COPY3=VENDOR COPY
PRINTCUSTOMERCOPY=1
AUTOMATIC_PRINT_MODE=0
RECEIPT_MERCHANT_PAPER=1
RECEIPT_CUSTOMER_PAPER=1
RECEIPT_FLY_RECEIPT=1
RECEIPT_E_NPI_DEMO=1
RECEIPT_E_PIXCEL=0
ELECSIGN_IS_SUPPORT=0

#===========================[SCANNER CONFIG]===========================
SCAN_PRIORITY_SCANNER=1
SCAN_EXTERN_CONNECT_MODE=0
SCAN_EXTERN_USB_WAIT_TIME=300
SCAN_EXTERN_SERIAL_BAUDRATE=115200

#===========================[PASSWORDS]===========================
PASSWORD_ADMIN=8D969EEF6ECAD3C29A3A629280E686CF0C3F5D5A86AFF3CA12020C923ADC6C92
PASSWORD_ADMIN_LENGTH=6
PASSWORD_SYSTEM_ADMIN=91B4D142823F7D20C5F08DF69122DE43F35F057A988D9619F6D3138485C9A203
PASSWORD_SYSTEM_ADMIN_LENGTH=6
PASSWORD_SECURITY=92925488B28AB12584AC8FCAA8A27A0F497B2C62940C8F4FBC8EF19EBC87C43E
PASSWORD_SECURITY_LENGTH=6
ADMINPWD=0000
USERPWD=0000
FUNCPWD=0000
SETTLEPWD=0000
ONOFFPWD=1111

#===========================[NETWORK & SYSTEM]===========================
TPDU=6000000000
NII=0001
TIMEOUT=30
SSLFLAG=0
COMMTYPE=3
SERVERIP1=192.168.111.7
PORT1=1165
SERVERIP2=192.168.111.7
PORT2=1165
TOMS_FLY_PARAMETERS=0
TOMS_FLY_RECEIPT=0
OTHER_TIP_INPUT=0
OTHER_SECOND_SCREEN_TOP=1

#===========================[BIN CONFIGURATION]===========================
ONUSBIN=16:4088600000000000:4088609999999999,16:4088890000000000
EMIBIN=16:4088600000000000:4088609999999999,16:4088890000000000
SALEBIN=16:4088600000000000:4088609999999999

#===========================[KEY SECTION]===========================
[KEY]
TPK=A12F0E6CC116120D61ACE42758EE3D17
INDEX=1